"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  BarChart3,
  Code2,
  Swords,
  Megaphone,
  Lock,
  ArrowRight,
  CheckCircle2,
  Zap,
  LayoutDashboard,
  Server,
  Database,
  TerminalSquare,
} from "lucide-react";
import Link from "next/link";

import type { LucideIcon } from "lucide-react";

interface TechStackItem {
  role: string;
  name: string;
  icon: LucideIcon;
  desc: string;
}

interface Competitor {
  name: string;
  type: string;
  weakness: string;
  angle: string;
}

interface MockProjectData {
  id: string;
  name: string;
  tagline: string;
  overview: {
    score: number;
    verdict: string;
    summary: string;
    strengths: string[];
    risks: string[];
  };
  architecture: {
    description: string;
    stack: TechStackItem[];
    schema: string;
  };
  competitors: Competitor[];
}

const mockProjectData = {
  id: "proj_123",
  name: "PrepChef",
  tagline: "Local meal prep marketplace",
  overview: {
    score: 84,
    verdict: "High Viability",
    summary: "Strong market demand, but requires precise local execution.",
    strengths: [
      "Capitalizes on the growing 'health-conscious but busy' demographic.",
      "Low overhead for chefs (using existing home or ghost kitchens).",
      "High retention rate for subscription meal preps.",
    ],
    risks: [
      "Two-sided marketplace 'cold start' problem.",
      "Strict local food safety and cottage food laws.",
      "Logistics of consistent delivery windows.",
    ],
  },
  architecture: {
    description:
      "Optimized for speed-to-market, low initial cost, and seamless payment splits.",
    stack: [
      {
        role: "Frontend",
        name: "Next.js + Tailwind",
        icon: LayoutDashboard,
        desc: "Fast SEO routing & clean UI.",
      },
      {
        role: "Backend / Auth",
        name: "Supabase",
        icon: Database,
        desc: "PostgreSQL, instant APIs, & social login.",
      },
      {
        role: "Payments",
        name: "Stripe Connect",
        icon: TerminalSquare,
        desc: "Handles split payments to chefs automatically.",
      },
    ],
    schema: `create table users (
    id uuid primary key,
    role text -- 'chef' or 'customer',
    full_name text
);

create table meals (
    id uuid primary key,
    chef_id uuid references users(id),
    price decimal,
    available_portions int
);`,
  },
  competitors: [
    {
      name: "UberEats / DoorDash",
      type: "Indirect",
      weakness:
        "Optimized for immediate restaurant delivery, not structured weekly meal prep. Very high fees.",
      angle:
        "Focus entirely on weekly subscriptions. Offer chefs 85% revenue share vs Uber's 70%.",
    },
    {
      name: "CookUnity",
      type: "Direct",
      weakness:
        "Operates out of centralized ghost kitchens, limiting availability to major tier-1 cities only.",
      angle:
        "Enable local cottage-law chefs. Expand rapidly into tier-2 and tier-3 suburbs where CookUnity cannot operate.",
    },
    {
      name: "Local Facebook Groups",
      type: "Direct (Status Quo)",
      weakness:
        "Zero trust mechanisms, manual Venmo payments, disorganized ordering process.",
      angle:
        "Bring trust (reviews), convenience (Stripe subscriptions), and discovery to the existing black market.",
    },
  ],
};

const TABS_CONFIG = [
  { id: "overview", label: "Executive Summary", icon: BarChart3 },
  { id: "tech", label: "Tech Stack Blueprint", icon: Code2 },
  { id: "competitors", label: "Competitor Matrix", icon: Swords },
  { id: "gtm", label: "Go-to-Market", icon: Megaphone, locked: true },
];

const Banner = () => (
  <div className="bg-violet-600 text-white text-sm font-medium py-2 px-4 rounded-t-2xl flex flex-col sm:flex-row items-center justify-between gap-2 text-center sm:text-left">
    <span>👀 You are viewing a sample report generated by DevLaunch AI.</span>
    <Link
      href="/signup"
      className="hover:text-violet-200 transition-colors flex items-center gap-1 whitespace-nowrap"
    >
      Create your own <ArrowRight className="w-4 h-4" />
    </Link>
  </div>
);

type SidebarProps = {
  project: MockProjectData;
  activeTab: string;
  setActiveTab: (tab: string) => void;
};

const Sidebar = ({ project, activeTab, setActiveTab }: SidebarProps) => (
  <div className="w-full md:w-64 bg-zinc-50 dark:bg-zinc-900/50 border-r border-zinc-200 dark:border-zinc-800 p-4 md:p-6 flex flex-col shrink-0">
    <div className="mb-4 md:mb-8 flex md:block items-center justify-between">
      <div>
        <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-1 md:mb-2">
          Project
        </p>
        <h2 className="text-lg font-bold text-zinc-900 dark:text-white leading-tight">
          {project.name}
        </h2>
        <p className="text-sm text-zinc-500 truncate hidden md:block">
          {project.tagline}
        </p>
      </div>

      <Link
        href="/signup"
        className="md:hidden flex items-center gap-2 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 px-3 py-2 rounded-lg text-xs font-semibold shadow-md"
      >
        Run Idea <Zap className="w-3 h-3 text-amber-500" />
      </Link>
    </div>

    <nav
      role="tablist"
      className="flex md:flex-col gap-2 overflow-x-auto md:overflow-visible pb-2 md:pb-0 flex-1 hide-scrollbar -mx-4 px-4 md:mx-0 md:px-0"
    >
      {TABS_CONFIG.map((tab) => (
        <button
          key={tab.id}
          role="tab"
          aria-selected={activeTab === tab.id}
          aria-controls={`panel-${tab.id}`}
          onClick={() => setActiveTab(tab.id)}
          className={`flex items-center gap-2 md:gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all relative whitespace-nowrap shrink-0 md:w-full ${
            activeTab === tab.id
              ? "text-violet-600 dark:text-violet-400"
              : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white hover:bg-zinc-100 dark:hover:bg-zinc-800/50"
          }`}
        >
          {activeTab === tab.id && (
            <motion.div
              layoutId="active-tab"
              className="absolute inset-0 bg-violet-100 dark:bg-violet-500/10 rounded-xl"
              transition={{ type: "spring", bounce: 0.2, duration: 0.6 }}
            />
          )}
          <tab.icon
            className={`w-4 h-4 relative z-10 ${activeTab === tab.id ? "text-violet-600 dark:text-violet-400" : ""}`}
          />
          <span className="relative z-10">{tab.label}</span>
          {tab.locked && (
            <Lock className="w-3.5 h-3.5 ml-1 md:ml-auto relative z-10 opacity-50" />
          )}
        </button>
      ))}
    </nav>

    <div className="hidden md:block pt-6 border-t border-zinc-200 dark:border-zinc-800 mt-auto">
      <Link
        href="/signup"
        className="w-full flex items-center justify-center gap-2 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all hover:bg-zinc-800 dark:hover:bg-zinc-100 shadow-md"
      >
        Run Your Idea
        <Zap className="w-4 h-4 text-amber-500" />
      </Link>
    </div>
  </div>
);

const TabOverview = ({ data }: { data: MockProjectData["overview"] }) => (
  <motion.div
    initial={{ opacity: 0, y: 10 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0, y: -10 }}
    className="max-w-3xl"
  >
    <div className="flex flex-col sm:flex-row sm:items-end gap-4 sm:gap-6 mb-10">
      <div className="w-20 h-20 sm:w-24 sm:h-24 shrink-0 rounded-full bg-green-50 dark:bg-green-500/10 border-4 border-green-100 dark:border-green-500/20 flex items-center justify-center text-2xl sm:text-3xl font-bold text-green-600 dark:text-green-400">
        {data.score}
      </div>
      <div className="pb-2">
        <h1 className="text-2xl sm:text-3xl font-bold text-zinc-900 dark:text-white mb-2">
          {data.verdict}
        </h1>
        <p className="text-zinc-500">{data.summary}</p>
      </div>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
      <div className="bg-zinc-50 dark:bg-zinc-900/50 p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800">
        <h3 className="text-sm font-bold text-zinc-900 dark:text-white uppercase tracking-wider mb-4 flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-green-500" /> Strengths
        </h3>
        <ul className="space-y-3 text-sm text-zinc-600 dark:text-zinc-400">
          {data.strengths.map((item, i) => (
            <li key={i}>• {item}</li>
          ))}
        </ul>
      </div>
      <div className="bg-zinc-50 dark:bg-zinc-900/50 p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800">
        <h3 className="text-sm font-bold text-zinc-900 dark:text-white uppercase tracking-wider mb-4 flex items-center gap-2">
          <Zap className="w-4 h-4 text-amber-500" /> Risks
        </h3>
        <ul className="space-y-3 text-sm text-zinc-600 dark:text-zinc-400">
          {data.risks.map((item, i) => (
            <li key={i}>• {item}</li>
          ))}
        </ul>
      </div>
    </div>
  </motion.div>
);

const TabTechStack = ({ data }: { data: MockProjectData["architecture"] }) => (
  <motion.div
    initial={{ opacity: 0, y: 10 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0, y: -10 }}
    className="max-w-4xl"
  >
    <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-2">
      Suggested Architecture
    </h2>
    <p className="text-zinc-500 mb-8">{data.description}</p>

    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
      {data.stack.map((tech, i) => (
        <div
          key={i}
          className="bg-white dark:bg-zinc-900 p-6 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-sm"
        >
          <div className="w-10 h-10 bg-violet-50 dark:bg-violet-500/10 text-violet-600 dark:text-violet-400 rounded-xl flex items-center justify-center mb-4">
            <tech.icon className="w-5 h-5" />
          </div>
          <p className="text-xs font-semibold text-violet-600 dark:text-violet-400 mb-1">
            {tech.role}
          </p>
          <h4 className="text-lg font-bold text-zinc-900 dark:text-white mb-2">
            {tech.name}
          </h4>
          <p className="text-sm text-zinc-500 leading-relaxed">{tech.desc}</p>
        </div>
      ))}
    </div>

    <div className="bg-zinc-950 p-6 rounded-2xl border border-zinc-800 text-zinc-300 font-mono text-sm overflow-x-auto shadow-inner whitespace-pre">
      <div className="flex gap-2 mb-4">
        <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
        <div className="w-3 h-3 rounded-full bg-amber-500/20 border border-amber-500/50"></div>
        <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50"></div>
      </div>
      <p className="text-zinc-500 mb-2"># Generated Database Schema (Core)</p>

      <div
        dangerouslySetInnerHTML={{
          __html: data.schema
            .replace(
              /create table/g,
              '<span class="text-violet-400">create table</span>',
            )
            .replace(/--.*/g, '<span class="text-zinc-500">$&</span>'),
        }}
      />
    </div>
  </motion.div>
);

const TabCompetitors = ({ data }: { data: MockProjectData["competitors"] }) => (
  <motion.div
    initial={{ opacity: 0, y: 10 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0, y: -10 }}
    className="max-w-4xl"
  >
    <h2 className="text-2xl font-bold text-zinc-900 dark:text-white mb-2">
      Market Analysis
    </h2>
    <p className="text-zinc-500 mb-8">
      Direct and indirect competitors, and your specific angles to beat them.
    </p>

    <div className="space-y-4">
      {data.map((comp, i) => (
        <div
          key={i}
          className="flex flex-col md:flex-row md:items-start gap-4 p-6 bg-zinc-50 dark:bg-zinc-900/50 rounded-2xl border border-zinc-200 dark:border-zinc-800"
        >
          <div className="w-full md:w-48 shrink-0">
            <h4 className="text-base font-bold text-zinc-900 dark:text-white">
              {comp.name}
            </h4>
            <span className="inline-block mt-1 text-[10px] font-bold uppercase tracking-wider text-violet-600 dark:text-violet-400 bg-violet-100 dark:bg-violet-500/10 px-2 py-0.5 rounded-full">
              {comp.type}
            </span>
          </div>
          <div className="flex-1 space-y-3">
            <div>
              <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-1">
                Their Weakness
              </p>
              <p className="text-sm text-zinc-600 dark:text-zinc-300">
                {comp.weakness}
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-green-600 dark:text-green-500 uppercase tracking-wider mb-1">
                Your Angle
              </p>
              <p className="text-sm text-zinc-600 dark:text-zinc-300 font-medium">
                {comp.angle}
              </p>
            </div>
          </div>
        </div>
      ))}
    </div>
  </motion.div>
);

const TabLocked = () => (
  <motion.div
    initial={{ opacity: 0 }}
    animate={{ opacity: 1 }}
    exit={{ opacity: 0 }}
    className="max-w-4xl h-full flex flex-col relative overflow-hidden rounded-2xl min-h-[400px]"
  >
    <div className="opacity-20 blur-[6px] select-none pointer-events-none p-6">
      <h2 className="text-2xl font-bold mb-4">Go-to-Market Strategy</h2>
      <div className="h-4 bg-zinc-300 dark:bg-zinc-700 w-3/4 rounded mb-2"></div>
      <div className="h-4 bg-zinc-300 dark:bg-zinc-700 w-full rounded mb-6"></div>
      <div className="grid grid-cols-2 gap-4 mb-8">
        <div className="h-32 bg-zinc-300 dark:bg-zinc-700 rounded-xl"></div>
        <div className="h-32 bg-zinc-300 dark:bg-zinc-700 rounded-xl"></div>
      </div>
      <div className="h-4 bg-zinc-300 dark:bg-zinc-700 w-1/2 rounded mb-2"></div>
      <div className="h-4 bg-zinc-300 dark:bg-zinc-700 w-5/6 rounded mb-2"></div>
    </div>

    <div className="absolute inset-0 z-10 flex items-center justify-center bg-white/40 dark:bg-zinc-950/40 backdrop-blur-sm p-6">
      <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 p-8 rounded-3xl shadow-2xl max-w-md text-center transform hover:scale-[1.02] transition-transform">
        <div className="w-16 h-16 bg-violet-100 dark:bg-violet-500/10 text-violet-600 dark:text-violet-400 rounded-full flex items-center justify-center mx-auto mb-6">
          <Lock className="w-8 h-8" />
        </div>
        <h3 className="text-xl font-bold text-zinc-900 dark:text-white mb-3">
          Unlock the Full Strategy
        </h3>
        <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-8">
          The Go-to-Market plan includes step-by-step instructions on acquiring
          your first 100 users, ideal customer profiles, and Day 1 marketing
          copy.
        </p>
        <Link
          href="/signup"
          className="flex items-center justify-center gap-2 w-full bg-violet-600 hover:bg-violet-700 text-white px-6 py-3.5 rounded-xl font-medium transition-all shadow-md shadow-violet-500/20"
        >
          Sign up to run your own idea
          <ArrowRight className="w-4 h-4" />
        </Link>
        <p className="mt-4 text-xs text-zinc-400">
          Join 1,000+ founders validating ideas today.
        </p>
      </div>
    </div>
  </motion.div>
);

export default function PublicReportDemo() {
  const [activeTab, setActiveTab] = useState("overview");

  return (
    <main className="min-h-screen bg-zinc-50 dark:bg-[#0A0A0A] pt-12 md:pt-24 pb-12 selection:bg-violet-500/30">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <Banner />

        <div className="bg-white dark:bg-zinc-950 border-x border-b border-zinc-200 dark:border-zinc-800 rounded-b-2xl shadow-2xl flex flex-col md:flex-row md:h-[calc(100vh-8rem)] md:min-h-[700px] overflow-hidden">
          <Sidebar
            project={mockProjectData}
            activeTab={activeTab}
            setActiveTab={setActiveTab}
          />

          <div
            id={`panel-${activeTab}`}
            role="tabpanel"
            aria-labelledby={activeTab}
            className="flex-1 overflow-y-auto p-4 sm:p-6 md:p-10 custom-scrollbar relative bg-white dark:bg-zinc-950"
          >
            <AnimatePresence mode="wait">
              {activeTab === "overview" && (
                <TabOverview key="overview" data={mockProjectData.overview} />
              )}
              {activeTab === "tech" && (
                <TabTechStack key="tech" data={mockProjectData.architecture} />
              )}
              {activeTab === "competitors" && (
                <TabCompetitors
                  key="competitors"
                  data={mockProjectData.competitors}
                />
              )}
              {activeTab === "gtm" && <TabLocked key="gtm" />}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </main>
  );
}
